config/routes.rb
Rails.application.routes.draw do
  get '/login',to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #get 'sessions/new'
  namespace :admin do
    resources :users
  end
  resources :works
  root to: 'works#index'
  post'/list',to: 'works#list'
  get'/list',to: 'works#list'
  get'/add', to: 'works#favorite_add'
  get'/favorite', to:'works#favorite_list'


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user),notice:"ユーザを登録しました"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_user_url, notice: "ユーザー「#{@user.name}」を削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
    ul#error_explanation
        - user.errors.full_messages.each do |message|
            li= message

= form_with model: [:admin, user], local: true do |f|
    .form-group
        = f.label :name, '名前'
        = f.text_field :name, class: 'form-control'
    .form-group
        = f.label :email, 'メールアドレス'
        = f.text_field :email, class: 'form-control'
    .form-check
        = f.label :admin, class: 'form-check-label' do
            = f.check_box :admin, class: 'form-check-input'
                | 管理者権限
    .form-group
        = f.label :password, 'パスワード'
        = f.password_field :password, class: 'form-control'
    .form-group
        = f.label :password_confirmation, 'パスワード(確認)'
        = f.password_field :password_confirmation, class: 'form-control'
    = f.submit '登録する',class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザ編集

.nav.justify-content-end
    = link_to '一覧',admin_users_path, class: 'nav-link'

= render partial: 'form', locals: {user: @user}

app/views/admin/users/index.html.slim
h1 ユーザ一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
    thead.thead-default
        tr 
            th= User.human_attribute_name(:name)
            th= User.human_attribute_name(:email)
            th= User.human_attribute_name(:admin)
            th= User.human_attribute_name(:created_at)
            th= User.human_attribute_name(:updated_at)
            th
    tbody
        - @users.each do |user|
            tr
                td= link_to user.name,[:admin, user]
                td= user.email
                td= user.admin? ? 'あり' : 'なし'
                td= user.created_at
                td= user.updated_at
                td
                    = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
                    = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザ「#{user.name}」を削除します．よろしいですか？"},class: 'btn btn-denger'
                

app/views/admin/users/new.html.slim
h1 ユーザ登録

.nav.justify-content-end
    = link_to '一覧',new_admin_user_path, class: 'nav-link'
= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザの詳細

.nav.justify-content-end
    =link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
    tbody
        tr
            th= User.human_attribute_name(:id)
            td= @user.id
        tr  
            th= User.human_attribute_name(:name)
            td= @user.name
        tr
            th= User.human_attribute_name(:email)
            td= @user.email
        tr
            th= User.human_attribute_name(:admin)
            td= @user.admin? ? 'あり' : 'なし'
        tr
            th= User.human_attribute_name(:created_at)
            td= @user.created_at
        tr  
            th= User.human_attribute_name(:updated_at)
            td= @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザ「#{@user.name}」を削除します．よろしいですか？"},class: 'btn btn-denger'