config/routes.rb
Rails.application.routes.draw do
  get '/login',to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #get 'sessions/new'
  namespace :admin do
    resources :users
  end
  resources :works
  root to: 'works#index'
  post'/list',to: 'works#list'
  get'/list',to: 'works#list'
  get'/add', to: 'works#favorite_add'
  get'/favorite', to:'works#favorite_list'


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Always Fresh
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = yield :css
    meta content="width=device-width,initial-scale=1.0" name="viewport" 
    script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.3.4/gsap.min.js"
    script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.3.4/ScrollTrigger.min.js"
    script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/DrawSVGPlugin3.min.js"
    script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/MotionPathPlugin.min.js"
    
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand AlwaysFresh

      ul.navbar-nav.ml-auto
        -if current_user
          li.nav-item= link_to 'タスク一覧', task_path, class: 'nav-link'
          li.nav-item= link_to 'ユーザ一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        -else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
          li.nav-item= link_to 'お気に入り', favorite_path, class: 'nav-link'

    .container
    = yield
    p.footer copyright Yuma-Aratake 2021
   
    